apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-pki2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-pki2
    app.kubernetes.io/part-of: load-app-c9788bb5-83db-4b8c-9707-1efbf8edd2e3
  name: devfile-sample-python-basic-pki2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-pki2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-pki2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-1-tenant/load-app-c9788bb5-83db-4b8c-9707-1efbf8edd2e3/devfile-sample-python-basic-pki2@sha256:53bed8c2ead4747c96143c844490fed8944015b661ac84fbd9a45feac4a91bcb
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
